export const APP_ROUTES = {
    HOME: "/",
    CONTACT: "/contact",
    ORGANIZING_COMMITTEE: "/committees/organizing-committee",
    PROGRAM_COMMITTEES: "/committees/program-committees",
    SPEAKERS: "/speakers",
    PROGRAM: "/program",
    SUBMISSION: "/submission/paper-submission",
    SUBMISSION_CAMERA_READY: "/submission/paper-submission/camera-ready",
    REGISTRATION: "/registration",
    TRAVEL_INFO: "/travel-information",
    TRAVEL_INFO_VISA: "/travel-information/visa",
    VENUE_CONFERENCE: "/venue/conference-venue",
    TRAVEL_INFO_ACCOMMODATION: "/travel-information/accommodation",
    CALL_OF_PAPER: "/call-for-paper", 
}